services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=tcg_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  scraper-api:
    image: ghcr.io/kaiserdrake/optcg-scraper
    restart: always

  backend:
    build: ./backend
    restart: always
    ports:
      - '3001:3001'
    volumes:
      - ./data:/usr/src/app/data
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://backend:3001
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  postgres_data:
